name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "1.9.12"
  ANCHOR_VERSION: "0.24.2"

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-build-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/clippy-check@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features
      - run: cargo build --verbose
      - run: cargo test --verbose

  anchor-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-anchor-build-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v3

      - name: Cache solana installation
        id: solana-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/solana/install
          key: ${{ runner.os }}-solana-v${{ env.SOLANA_VERSION }}

      - name: Install solana
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

      - name: Add solana to PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - run: solana-keygen new --no-bip39-passphrase

      - name: Cache anchor installation
        id: anchor-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/anchor
          key: ${{ runner.os }}-anchor-v${{ env.ANCHOR_VERSION }}

      - name: Install anchor
        if: steps.anchor-cache.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked

      - name: Show versions
        run: |
          cargo --version
          solana --version
          anchor --version

      - name: Build
        run: anchor build --skip-lint

      - name: Run tests
        run: sh ./tests/run-anchor-tests.sh
        env:
          SIGNATORY_PRIV_KEY: ${{ secrets.SIGNATORY_PRIV_KEY }}
          SIGNATORY_COMMITMENT: processed
          SIGNATORY_PROGRAM_ID: DFLoSPFeB6VWYX3UZAz16XRmhJJrUWxjazgBVBSSaqHX